- - 日常购物
  - 母婴用品
  - [备注]
- - 衣服饰品
  - 衣服裤子
  - [备注]
- - 衣服饰品
  - 鞋帽包包
  - [备注]
- - 衣服饰品
  - 化妆饰品
  - [备注]
- - 食品酒水
  - 菜品调料
  - [备注]
- - 食品酒水
  - 早午晚餐
  - [备注]
- - 食品酒水
  - 烟酒茶
  - [备注]
- - 食品酒水
  - 水果零食
  - [备注]
- - 居家物业
  - 日常用品
  - [备注]
- - 居家物业
  - 水电煤气
  - [备注]
- - 居家物业
  - 房租
  - [备注]
- - 居家物业
  - 物业管理
  - [备注]
- - 居家物业
  - 维修保养
  - [备注]
- - 行车交通
  - 公共交通
  - [备注]
- - 行车交通
  - 打车租车
  - [备注]
- - 行车交通
  - 私家车费用
  - [备注]
- - 交流通讯
  - 座机费
  - [备注]
- - 交流通讯
  - 手机费
  - [备注]
- - 交流通讯
  - 上网费
  - [备注]
- - 交流通讯
  - 邮寄费
  - [备注]
- - 休闲娱乐
  - 聚会
  - [备注]
- - 休闲娱乐
  - 聚餐
  - [备注]
- - 休闲娱乐
  - 运动健身
  - [备注]
- - 休闲娱乐
  - 腐败聚会
  - [备注]
- - 休闲娱乐
  - 休闲玩乐
  - [备注]
- - 休闲娱乐
  - 宠物宝贝
  - [备注]
- - 休闲娱乐
  - 旅游度假
  - [备注]
- - 学习进修
  - 书报杂志
  - [备注]
- - 学习进修
  - 培训进修
  - [备注]
- - 学习进修
  - 数码装备
  - [备注]
- - 人情往来
  - 送礼请客
  - [备注]
- - 人情往来
  - 孝敬家长
  - [备注]
- - 人情往来
  - 还人钱物
  - [备注]
- - 人情往来
  - 慈善捐助
  - [备注]
- - 医疗保健
  - 理发
  - [备注]
- - 医疗保健
  - 药品费
  - [备注]
- - 医疗保健
  - 保健费
  - [备注]
- - 医疗保健
  - 美容费
  - [备注]
- - 医疗保健
  - 治疗费
  - [备注]
- - 金融保险
  - 银行手续
  - [备注]
- - 金融保险
  - 投资亏损
  - [备注]
- - 金融保险
  - 按揭还款
  - [备注]
- - 金融保险
  - 消费税收
  - [备注]
- - 金融保险
  - 利息支出
  - [备注]
- - 金融保险
  - 赔偿罚款
  - [备注]
- - 其他杂项
  - 其他支出
  - [备注]
- - 其他杂项
  - 意外丢失
  - [备注]
- - 其他杂项
  - 烂账损失
  - [备注]
